ARG OPENWRT_VERSION=24.10.4
ARG OPENWRT_ARCH=mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64
ARG REPO_OWNER=maksimkurb

FROM ghcr.io/${REPO_OWNER}/openwrt-sdk:${OPENWRT_VERSION}-${OPENWRT_ARCH}

ARG OPENWRT_VERSION=24.10.4
ARG OPENWRT_ARCH=mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64

# Copy packages folder
COPY --chown=me:me configs /home/me/openwrt/owrt-configs
COPY --chown=me:me packages /home/me/openwrt/owrt-packages

RUN ./owrt-packages/compile.sh
