ARG OPENWRT_VERSION_GIT_REF=openwrt-24.10
ARG ROUTER_CONFIG=glinet-mt6000
ARG REPO_OWNER=maksimkurb

FROM ghcr.io/${REPO_OWNER}/openwrt-builder:${OPENWRT_VERSION_GIT_REF}-${ROUTER_CONFIG}

# Copy packages folder
COPY --chown=me:me packages /home/me/openwrt/owrt-packages

RUN ./owrt-packages/compile.sh
